telegram:
  api_id:
  api_hash: ''
  phone_number: ''
  bot:
    token: ""
    chatId:

trade:
  equity99:
    max_open_trades: 2
    fund_alloc: 2000
  AngelOneAdvisory:
    max_open_trades: 2
    fund_alloc: 2000
  CustomChannel:
    max_open_trades: 2
    fund_alloc: 1000

derivative:
  dry_run: true
  dry_cash: 20000
  conf:
    AngelOneAdvisory:
      max_open_trades: 2
      lot_count: 1